// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZGWX_vokaWA_zjk5vHhn0T2HCyQVSO4Y',
    appId: '1:10033794531:web:da0cb41eb35cb2cb6a64d6',
    messagingSenderId: '10033794531',
    projectId: 'product-explorer-e06d1',
    authDomain: 'product-explorer-e06d1.firebaseapp.com',
    databaseURL: 'https://product-explorer-e06d1-default-rtdb.firebaseio.com',
    storageBucket: 'product-explorer-e06d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0shmjgCvjxibrLsOfHZomKfB7oCFmG30',
    appId: '1:10033794531:android:3fe6117c7d448c326a64d6',
    messagingSenderId: '10033794531',
    projectId: 'product-explorer-e06d1',
    databaseURL: 'https://product-explorer-e06d1-default-rtdb.firebaseio.com',
    storageBucket: 'product-explorer-e06d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP5HprN65dtJGoY6m4TZgqxS6apyKX928',
    appId: '1:10033794531:ios:cba2b6c10f6b7bf46a64d6',
    messagingSenderId: '10033794531',
    projectId: 'product-explorer-e06d1',
    databaseURL: 'https://product-explorer-e06d1-default-rtdb.firebaseio.com',
    storageBucket: 'product-explorer-e06d1.firebasestorage.app',
    iosBundleId: 'com.example.aurifyTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP5HprN65dtJGoY6m4TZgqxS6apyKX928',
    appId: '1:10033794531:ios:cba2b6c10f6b7bf46a64d6',
    messagingSenderId: '10033794531',
    projectId: 'product-explorer-e06d1',
    databaseURL: 'https://product-explorer-e06d1-default-rtdb.firebaseio.com',
    storageBucket: 'product-explorer-e06d1.firebasestorage.app',
    iosBundleId: 'com.example.aurifyTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZGWX_vokaWA_zjk5vHhn0T2HCyQVSO4Y',
    appId: '1:10033794531:web:fa7c4dfff5760d136a64d6',
    messagingSenderId: '10033794531',
    projectId: 'product-explorer-e06d1',
    authDomain: 'product-explorer-e06d1.firebaseapp.com',
    databaseURL: 'https://product-explorer-e06d1-default-rtdb.firebaseio.com',
    storageBucket: 'product-explorer-e06d1.firebasestorage.app',
  );
}
